### ISSUE TITLE
Docker pull error when pulling `latest` tag

### ISSUE THREAD

**Issue by MichailVestnik** [albertito/chasquid#21]
Hi! 

![Снимок экрана от 2021-08-14 13-37-51](https://user-images.githubusercontent.com/87961969/129434184-45550b77-2ea5-4bf3-988d-983dda28c841.png)

**Comment by albertito** [comment]
Thank you for the report!

For ease of reference, this is the key part of the screenshot:

```
$ docker pull albertito/chasquid
Using default tag: latest
Error response from daemon: manifest for albertito/chasquid:latest not found: manifest unknown: manifest unknown
```

**Comment by albertito** [comment]
The `:latest` tag does not exist. It isn't automatically created.

Please use `:master` (or `:next` for the testing version), as documented in https://blitiri.com.ar/p/chasquid/docker/ and https://hub.docker.com/r/albertito/chasquid.

That said, since `:latest` is the default when the tag is omitted, I will adjust the build system to also tag `:master` with it to avoid similar issues in the future.

**Comment by albertito** [comment]
Commit 4bd2b9e3c0 fixes this, you can now just do `docker pull albertito/chasquid`.

Thanks again for reporting this.
