### ISSUE TITLE
Allow alias '*' to redirect all email

### ISSUE THREAD

**Issue by DavidVentura** [albertito/chasquid#5]
Hi

Some sites do not allow the usage of `+` in email addresses (they are considered invalid). It'd be great if I could specify that any email[1] should be redirected to another's address:

```
*: david@mail
```

[1]: Ideally a \* means that any email not matching an existing account (and alias?) gets forwarded, but that is not important for me

**Comment by foxcpp** [comment]
Note that such configuration is potentially unsafe for use in public-facing email server. Bots probing addresses will see that all addresses "exist", this might attract a lot of spam or other unwanted messages. 

I would use a prefix like `david-` in this case.

Check `suffix_separators` option in configuration, you can probably add `-` there and use it instead of `+`.

**Comment by albertito** [comment]
Adding to @foxcpp's answer which I think is spot on.

I use `suffix_separators` with `-` to work around the `+` problem and it has been fairly effective.
You can see the details of that option in the [manpage](https://github.com/albertito/chasquid/blob/next/docs/man/chasquid.conf.5.pod).

If you really really want a catch-all alias, it can be done in a hacky way with [alias hooks](https://blitiri.com.ar/p/chasquid/hooks/#alias-resolve-hook). I don't recommend it but the possibility is there.

Do these cover your use case?

**Comment by DavidVentura** [comment]
I think these 2 possibilities are enough to cover what I need, thanks
