### ISSUE TITLE
mail to/from IP address, or just document how

### ISSUE THREAD

**Issue by rkiddy** [albertito/chasquid#50]
I am trying this on my ubuntu server. I serve several domains from this service, so using certbot does not scare me.

But I want to try it, at first, without messing with the DNS stuff. I will try this and, perhaps, suggest changes to documentation.

I think a bit added to the install/config docs can show:
- install the server software
- minimally configure
- send an email from something to something

I think this would be a good thing to add.

**Comment by albertito** [comment]
Thank you for filing this!

chasquid does require at least a domain to be set up in order to run. This is part of making it "hard to misconfigure".

But I agree with you it makes the initial setup a bit more difficult, as it requires DNS and certificates to be configured, which is a non-trivial amount of work. You're going to need to do all of that in any case, but chasquid makes you do it _before_ is up and running for the first time.

[The how-to](https://blitiri.com.ar/p/chasquid/howto/) tries to help guide people through this process, to make it more manageable. I think that's a minimal functioning setup, and hopefully helps with what you're asking for?

One thing to note is that the domain that you use for the initial setup doesn't have to be the final one. You can start with a "test" subdomain, try things out, and only add the main ones you're happy with things.

Does that help at all?

Thanks again!

**Comment by rkiddy** [comment]
It does. I will check whether using a "temporary" domain helps me.

In the meantime, installing (and then uninstalling) chasquid has (I believe) made it so that I no longer receive e-mails from my host. I used to get emails from the stdout of my cron jobs and I am not getting them now. I will investigate to see what may have happened, but if you have any suggestions, it would be much appreciated.

**Comment by albertito** [comment]
> It does. I will check whether using a "temporary" domain helps me.

Thank you, please let me know how it goes.


> In the meantime, installing (and then uninstalling) chasquid has (I believe) made it so that I no longer receive e-mails from my host. I used to get emails from the stdout of my cron jobs and I am not getting them now. I will investigate to see what may have happened, but if you have any suggestions, it would be much appreciated.

That is likely to be unrelated to chasquid itself, but if you uninstalled another MTA (like exim or postfix), they often provide `/usr/sbin/sendmail`, which is what cron uses.

So by uninstalling another package it's possible you no longer has that binary, which cron needs to deliver mail.

If that's the case, you can use a package like `msmtp-mta` which provides `/usr/sbin/sendmail` and lets you use any server (including a local or remote chasquid).

I hope this helps!

**Comment by rkiddy** [comment]
Well, something happened and I got the last 14 days of emails in one big bunch. I had not uninstalled or re-installed anything, as far as I know.

You know, do not worry about me over here. I obviously do not know quite enough to use this tool and I can try to figure this stuff out without bothering you.

I appreciate your positive responses, though. Much thanx.

**Comment by albertito** [comment]
No worries!

Regardless of the MTA you end up using, learning these things for the first time can be tricky, but IMO once you get the hang of it, you learn a lot and it can be very rewarding!

If it would help, you can also ask on irc, `#chasquid` on [OFTC](https://oftc.net/).

Thank you!
